# CI/CD Report Template
# Phase 10: CI/CD Pipeline (DevOps Engineer)
#
# Full build/test/lint/type-check pipeline results.
# Consumed by gate decision.

# --- Handoff envelope (standard for all 13 phases) ---
phase: 10
phase_name: ci_cd
role: devops
status: complete
timestamp: "2026-01-28T00:00:00Z"
depends_on: qa
_schema_version: "1.0"

summary: |
  CI pipeline passed. Build green, lint clean, types clean.

outputs:
  - .sprint/ci-report.yaml

open_issues: []

signals:
  pass: true
  confidence: high
  blockers: []

# --- Phase-specific body ---

# REQUIRED: Pipeline execution results
pipeline:
  build_status: success  # success | failure
  lint_clean: true
  type_check_clean: true
  duration_seconds: 120

# Individual step results
steps:
  - name: build
    status: success
    duration_seconds: 30

  - name: test
    status: success
    duration_seconds: 60
    details: "42 passed, 0 failed"

  - name: lint
    status: success
    duration_seconds: 15
    details: "No issues found"

  - name: type_check
    status: success
    duration_seconds: 15
    details: "No type errors"

# CI summary for gate decision
ci_summary:
  pass: true
  build_status: success
  lint_clean: true
  type_check_clean: true
