# CI Report Template
# Phase 10: Pull Request & CI (DevOps Engineer)
#
# Gate decision, PR creation, and GitHub CI pipeline results.
# The gate decision runs before PR creation (reads Phases 7-9).
# CI runs on GitHub after the PR is created.

# --- Handoff envelope (standard for all 13 phases) ---
phase: 10
phase_name: ci_cd
role: devops
status: complete
timestamp: "2026-01-28T00:00:00Z"
depends_on: security_review
_schema_version: "1.0"

summary: |
  Gate decision: SHIP. PR #42 created. CI pipeline passed.

outputs:
  - .sprint/ci-report.yaml

open_issues: []

signals:
  pass: true
  confidence: high
  blockers: []

# --- Phase-specific body ---

# REQUIRED: Pipeline execution results (from GitHub CI)
pipeline:
  build_status: success  # success | failure
  lint_clean: true
  type_check_clean: true
  duration_seconds: 120

# Individual CI step results
steps:
  - name: build
    status: success
    duration_seconds: 30

  - name: test
    status: success
    duration_seconds: 60
    details: "42 passed, 0 failed"

  - name: lint
    status: success
    duration_seconds: 15
    details: "No issues found"

  - name: type_check
    status: success
    duration_seconds: 15
    details: "No type errors"

# Pull request details
pr:
  number: 42
  url: "https://github.com/org/repo/pull/42"
  branch: "feature/my-feature"
  target_branch: main

# Gate decision (from skills/gate-decision/, runs before PR creation)
gate_decision:
  verdict: SHIP  # SHIP | REVISE | BLOCKED
  timestamp: "2026-01-28T00:00:00Z"
  rationale: |
    All signals green. Code review approved, no security findings,
    all tests passing with 87% coverage.

  signal_summary:
    code_review:
      pass: true
      unresolved_issues: 0
      severity_max: info
    qa:
      pass: true
      tests_passing: "42/42"
      coverage: 87
      lint_clean: true
      type_check_clean: true
      acceptance_criteria_met: "2/2"
    security_review:
      pass: true
      vulnerabilities: 0
      severity_max: none
    sentinel:
      pass: true
      blocking_count: 0
      total_issues: 3
      has_report: true

  blockers: []
  action: "Create pull request"
