# Sprint Product Template
# Phase 2: Refinement
#
# Transforms developer input into structured product requirements.
# Uses standard agile artifacts: epics, user stories, acceptance criteria.

# --- Handoff envelope (standard for all 13 phases) ---
phase: 2
phase_name: refinement
role: product_manager
status: complete
timestamp: "2026-01-28T00:00:00Z"
depends_on: intake
_schema_version: "1.0"

summary: |
  Transformed developer input into structured product requirements with user stories and acceptance criteria.

# --- Phase-specific body ---

# Epic: High-level feature container
epic:
  title: "Epic Title"
  description: |
    High-level description of the feature or capability.
    This groups related user stories together.
  business_value: |
    Why this matters to the business or users.
    Derived from the 'why' in input.

# User Stories: Individual deliverables
user_stories:
  - id: US-001
    as_a: "user type"
    i_want: "capability or feature"
    so_that: "benefit or value"
    acceptance_criteria:
      - "Given <context>, when <action>, then <result>"
      - "Given <context>, when <action>, then <result>"
    priority: must  # must | should | could | wont (MoSCoW)
    notes: "Optional implementation notes"

  - id: US-002
    as_a: "user type"
    i_want: "another capability"
    so_that: "another benefit"
    acceptance_criteria:
      - "Criterion 1"
      - "Criterion 2"
    priority: should

# Success Metrics: How we know it's working
success_metrics:
  - metric: "Response time < 200ms"
    measurement: "API monitoring"
  - metric: "User adoption > 50%"
    measurement: "Analytics tracking"

# Scope Boundaries
scope:
  in_scope:
    - "Feature A"
    - "Feature B"
  out_of_scope:
    - "Feature C (future iteration)"
    - "Feature D (different team)"
  assumptions:
    - "Users are already authenticated"
    - "Data exists in current format"

# Integration Requirements: External touchpoints
integration_requirements:
  - system: "Existing System Name"
    type: "API call / Database / Event"
    details: "How they integrate"

# --- Standard handoff footer ---
outputs:
  - .sprint/product.yaml

open_issues: []

signals:
  pass: true
  confidence: high
  blockers: []
